
-- create
CREATE TABLE MENU (
  Food varchar(255) PRIMARY KEY,
  Price INTEGER NOT NULL
);

-- insert
INSERT INTO MENU VALUES ('BBQ', 200);
INSERT INTO MENU VALUES ('Shrimp', 350);
INSERT INTO MENU VALUES ('Pizza', 500);
INSERT INTO MENU VALUES ('Beef Steak', 320);
INSERT INTO MENU VALUES ("Sisig", 200);

-- fetch 
SELECT * FROM MENU WHERE Food = 'Sisig';

